from .listplayers_c import ListPlayersC
from .createplayer_c import CreatePlayerC
from .deleteplayer_c import DeletePlayerC
from .homepage_c import HomepageC
from .manageplayer_c import ManagePlayerC
from .createtournament_c import CreateTournamentC
from .managetournaments_c import ManageTournamentC
from .listtournaments_c import ListTournamentsC
from .deletetournament_c import DeleteTournamentC